import type { Issue, Worker } from './types'

export const WORKERS: Worker[] = [
  { id: 'W001', name: 'Rajesh Kumar',  initials: 'RK', team: 'Road Maintenance',   distance: '1.2 km', available: true,  activeTasks: 2, performance: 94, phone: '+91 98200 11111' },
  { id: 'W002', name: 'Amit Sharma',   initials: 'AS', team: 'Water & Sanitation', distance: '2.4 km', available: true,  activeTasks: 1, performance: 88, phone: '+91 98200 22222' },
  { id: 'W003', name: 'Suresh Patil',  initials: 'SP', team: 'Road Maintenance',   distance: '3.1 km', available: false, activeTasks: 3, performance: 91, phone: '+91 98200 33333' },
  { id: 'W004', name: 'Priya Desai',   initials: 'PD', team: 'Electrical Works',   distance: '1.8 km', available: true,  activeTasks: 1, performance: 96, phone: '+91 98200 44444' },
  { id: 'W005', name: 'Mohan Yadav',   initials: 'MY', team: 'Drainage & Civil',   distance: '2.9 km', available: true,  activeTasks: 2, performance: 87, phone: '+91 98200 55555' },
]

export const INITIAL_ISSUES: Issue[] = [
  {
    id: 'CF-10482',
    citizenName: 'Meera Joshi',
    citizenId: 'C001',
    type: 'Pothole',
    description: 'Large pothole near City Center. Very dangerous for two-wheelers, almost caused an accident yesterday.',
    location: 'MG Road, Pune',
    address: 'MG Road, near Hotel Regency, Pune 411001',
    ward: 'Ward 5',
    priority: 'urgent',
    status: 'in_progress',
    submittedAt: '16 Aug 2026, 09:42 AM',
    aiCategory: 'Road Damage — Pothole',
    aiConfidence: 94,
    aiSeverity: 'High',
    assignedWorkerId: 'W001',
    assignedWorkerName: 'Rajesh Kumar',
    cx: 310, cy: 195,
    updates: [
      { time: '09:42 AM', message: 'Issue submitted by citizen', by: 'Meera Joshi', byRole: 'citizen' },
      { time: '09:43 AM', message: 'AI classified: Pothole, 94% confidence, High severity', by: 'AI System', byRole: 'ai' },
      { time: '10:05 AM', message: 'Assigned to Rajesh Kumar — Road Maintenance', by: 'Admin PMC', byRole: 'authority' },
      { time: '10:28 AM', message: 'Task accepted. En route to location.', by: 'Rajesh Kumar', byRole: 'worker' },
      { time: '11:15 AM', message: 'Repair crew on site, materials deployed.', by: 'Rajesh Kumar', byRole: 'worker' },
    ],
  },
  {
    id: 'CF-10479',
    citizenName: 'Arjun Patil',
    citizenId: 'C002',
    type: 'Garbage',
    description: 'Overflowing garbage bin not collected since 3 days. Very unhygienic and smell is unbearable.',
    location: 'Shivaji Nagar, Ward 5',
    address: 'Near Bus Stop, Shivaji Nagar, Pune 411005',
    ward: 'Ward 5',
    priority: 'high',
    status: 'proof_submitted',
    submittedAt: '16 Aug 2026, 07:15 AM',
    aiCategory: 'Sanitation — Garbage Overflow',
    aiConfidence: 91,
    aiSeverity: 'High',
    assignedWorkerId: 'W002',
    assignedWorkerName: 'Amit Sharma',
    proofDescription: 'Bin cleared and area cleaned. Waste taken to disposal unit.',
    cx: 490, cy: 130,
    updates: [
      { time: '07:15 AM', message: 'Issue submitted by citizen', by: 'Arjun Patil', byRole: 'citizen' },
      { time: '07:16 AM', message: 'AI classified: Garbage Overflow, 91% confidence', by: 'AI System', byRole: 'ai' },
      { time: '08:00 AM', message: 'Assigned to Amit Sharma — Water & Sanitation', by: 'Admin PMC', byRole: 'authority' },
      { time: '08:30 AM', message: 'Task accepted.', by: 'Amit Sharma', byRole: 'worker' },
      { time: '10:45 AM', message: 'Clearance done. Proof photo uploaded.', by: 'Amit Sharma', byRole: 'worker' },
    ],
  },
  {
    id: 'CF-10476',
    citizenName: 'Sangeeta Rao',
    citizenId: 'C003',
    type: 'Streetlight',
    description: 'Streetlight has been non-functional for 5 days. The area is completely dark at night, unsafe for women.',
    location: 'FC Road, Pune',
    address: 'FC Road, near Cummins College, Pune 411016',
    ward: 'Ward 8',
    priority: 'medium',
    status: 'assigned',
    submittedAt: '15 Aug 2026, 08:30 PM',
    aiCategory: 'Infrastructure — Streetlight Failure',
    aiConfidence: 88,
    aiSeverity: 'Medium',
    assignedWorkerId: 'W004',
    assignedWorkerName: 'Priya Desai',
    cx: 175, cy: 310,
    updates: [
      { time: '08:30 PM', message: 'Issue submitted by citizen', by: 'Sangeeta Rao', byRole: 'citizen' },
      { time: '08:31 PM', message: 'AI classified: Streetlight Failure, 88% confidence', by: 'AI System', byRole: 'ai' },
      { time: '09:00 AM', message: 'Assigned to Priya Desai — Electrical Works', by: 'Admin PMC', byRole: 'authority' },
    ],
  },
  {
    id: 'CF-10471',
    citizenName: 'Vikram Singh',
    citizenId: 'C004',
    type: 'Water Leakage',
    description: 'Burst water pipe flooding the road. Water wasted for 2 days. Road is slippery.',
    location: 'Koregaon Park, Ward 8',
    address: 'Lane 6, Koregaon Park, Pune 411001',
    ward: 'Ward 8',
    priority: 'urgent',
    status: 'resolved',
    submittedAt: '14 Aug 2026, 02:10 PM',
    aiCategory: 'Water Supply — Pipe Leakage',
    aiConfidence: 97,
    aiSeverity: 'Critical',
    assignedWorkerId: 'W002',
    assignedWorkerName: 'Amit Sharma',
    resolvedAt: '15 Aug 2026, 04:30 PM',
    cx: 580, cy: 270,
    updates: [
      { time: '02:10 PM', message: 'Issue submitted by citizen', by: 'Vikram Singh', byRole: 'citizen' },
      { time: '02:10 PM', message: 'AI classified: Water Pipe Leakage, 97% confidence, Critical severity', by: 'AI System', byRole: 'ai' },
      { time: '02:45 PM', message: 'Assigned to Amit Sharma — Water & Sanitation', by: 'Admin PMC', byRole: 'authority' },
      { time: '03:00 PM', message: 'On my way. Have called for support crew.', by: 'Amit Sharma', byRole: 'worker' },
      { time: '04:00 PM', message: 'Pipe repaired. Road drying.', by: 'Amit Sharma', byRole: 'worker' },
      { time: '04:25 PM', message: 'Proof uploaded. Ready for verification.', by: 'Amit Sharma', byRole: 'worker' },
      { time: '04:30 PM', message: 'Resolution verified. Issue closed and citizen notified.', by: 'Admin PMC', byRole: 'authority' },
    ],
  },
  {
    id: 'CF-10485',
    citizenName: 'Priya Nair',
    citizenId: 'C005',
    type: 'Drain Blockage',
    description: 'Storm drain completely blocked. Water logged on road after every rain. Children and elderly at risk.',
    location: 'Kothrud, Ward 16',
    address: 'Paud Road, Kothrud, Pune 411038',
    ward: 'Ward 16',
    priority: 'high',
    status: 'open',
    submittedAt: '16 Aug 2026, 06:00 AM',
    aiCategory: 'Drainage — Storm Drain Blockage',
    aiConfidence: 89,
    aiSeverity: 'High',
    cx: 400, cy: 350,
    updates: [
      { time: '06:00 AM', message: 'Issue submitted by citizen', by: 'Priya Nair', byRole: 'citizen' },
      { time: '06:01 AM', message: 'AI classified: Drain Blockage, 89% confidence. No duplicate found.', by: 'AI System', byRole: 'ai' },
    ],
  },
  {
    id: 'CF-10488',
    citizenName: 'Rahul Mehta',
    citizenId: 'C006',
    type: 'Pothole',
    description: 'Small pothole forming near school gate.',
    location: 'Aundh, Ward 12',
    address: 'Aundh Road, near DPS School, Pune 411007',
    ward: 'Ward 12',
    priority: 'medium',
    status: 'duplicate',
    duplicateOf: 'CF-10482',
    submittedAt: '16 Aug 2026, 11:00 AM',
    aiCategory: 'Road Damage — Pothole',
    aiConfidence: 87,
    aiSeverity: 'Medium',
    cx: 660, cy: 390,
    updates: [
      { time: '11:00 AM', message: 'Issue submitted by citizen', by: 'Rahul Mehta', byRole: 'citizen' },
      { time: '11:01 AM', message: 'AI detected potential duplicate of CF-10482 (83% similarity). Flagged as duplicate.', by: 'AI System', byRole: 'ai' },
    ],
  },
]
